const allStocks = [
  { simble: 'ABEV3', name: 'AMBEV S/A', type: 'ON' },
  { simble: 'AZUL4', name: 'AZUL', type: 'PN N2' },
  { simble: 'B3SA3', name: 'B3', type: 'ON NM' },
  { simble: 'BBAS3', name: 'BRASIL', type: 'ON NM' },
  { simble: 'BBDC3', name: 'BRADESCO', type: 'ON N1' },
  { simble: 'BBDC4', name: 'BRADESCO', type: 'PN N1' },
  { simble: 'BBSE3', name: 'BBSEGURIDADE', type: 'ON ED NM' },
  { simble: 'BEEF3', name: 'MINERVA', type: 'ON NM' },
  { simble: 'BPAC11', name: 'BTGP BANCO', type: 'UNT N2' },
  { simble: 'BRAP4', name: 'BRADESPAR', type: 'PN N1' },
  { simble: 'BRDT3', name: 'PETROBRAS BR', type: 'ON NM' },
  { simble: 'BRFS3', name: 'BRF SA', type: 'ON NM' },
  { simble: 'BRKM5', name: 'BRASKEM', type: 'PNA N1' },
  { simble: 'BRML3', name: 'BR MALLS PAR', type: 'ON NM' },
  { simble: 'BTOW3', name: 'B2W DIGITAL', type: 'ON NM' },
  { simble: 'CCRO3', name: 'CCR SA', type: 'ON NM' },
  { simble: 'CIEL3', name: 'CIELO', type: 'ON NM' },
  { simble: 'CMIG4', name: 'CEMIG', type: 'PN N1' },
  { simble: 'COGN3', name: 'COGNA ON', type: 'ON NM' },
  { simble: 'CPFE3', name: 'CPFL ENERGIA', type: 'ON NM' },
  { simble: 'CRFB3', name: 'CARREFOUR BR', type: 'ON NM' },
  { simble: 'CSAN3', name: 'COSAN', type: 'ON NM' },
  { simble: 'CSNA3', name: 'SID NACIONAL', type: 'ON' },
  { simble: 'CVCB3', name: 'CVC BRASIL', type: 'ON NM' },
  { simble: 'CYRE3', name: 'CYRELA REALT', type: 'ON NM' },
  { simble: 'ECOR3', name: 'ECORODOVIAS', type: 'ON NM' },
  { simble: 'EGIE3', name: 'ENGIE BRASIL', type: 'ON ED NM' },
  { simble: 'ELET3', name: 'ELETROBRAS', type: 'ON N1' },
  { simble: 'ELET6', name: 'ELETROBRAS', type: 'PNB N1' },
  { simble: 'EMBR3', name: 'EMBRAER', type: 'ON NM' },
  { simble: 'ENBR3', name: 'ENERGIAS BR', type: 'ON NM' },
  { simble: 'ENGI11', name: 'ENERGISA', type: 'UNT N2' },
  { simble: 'EQTL3', name: 'EQUATORIAL', type: 'ON NM' },
  { simble: 'FLRY3', name: 'FLEURY', type: 'ON NM' },
  { simble: 'GGBR4', name: 'GERDAU', type: 'PN N1' },
  { simble: 'GNDI3', name: 'INTERMEDICA', type: 'ON NM' },
  { simble: 'GOAU4', name: 'GERDAU MET', type: 'PN N1' },
  { simble: 'GOLL4', name: 'GOL', type: 'PN N2' },
  { simble: 'HAPV3', name: 'HAPVIDA', type: 'ON NM' },
  { simble: 'HGTX3', name: 'CIA HERING', type: 'ON NM' },
  { simble: 'HYPE3', name: 'HYPERA', type: 'ON NM' },
  { simble: 'IGTA3', name: 'IGUATEMI', type: 'ON NM' },
  { simble: 'IRBR3', name: 'IRBBRASIL RE', type: 'ON EX NM' },
  { simble: 'ITSA4', name: 'ITAUSA', type: 'PN ED N1' },
  { simble: 'ITUB4', name: 'ITAUUNIBANCO', type: 'PN EJ N1' },
  { simble: 'JBSS3', name: 'JBS', type: 'ON NM' },
  { simble: 'KLBN11', name: 'KLABIN S/A', type: 'UNT N2' },
  { simble: 'LAME4', name: 'LOJAS AMERIC', type: 'PN N1' },
  { simble: 'LREN3', name: 'LOJAS RENNER', type: 'ON NM' },
  { simble: 'MGLU3', name: 'MAGAZ LUIZA', type: 'ON NM' },
  { simble: 'MRFG3', name: 'MARFRIG', type: 'ON NM' },
  { simble: 'MRVE3', name: 'MRV', type: 'ON NM' },
  { simble: 'MULT3', name: 'MULTIPLAN', type: 'ON N2' },
  { simble: 'NTCO3', name: 'GRUPO NATURA', type: 'ON NM' },
  { simble: 'PCAR3', name: 'P.ACUCAR-CBD', type: 'ON NM' },
  { simble: 'PETR3', name: 'PETROBRAS', type: 'ON N2' },
  { simble: 'PETR4', name: 'PETROBRAS', type: 'PN N2' },
  { simble: 'QUAL3', name: 'QUALICORP', type: 'ON NM' },
  { simble: 'RADL3', name: 'RAIADROGASIL', type: 'ON NM' },
  { simble: 'RAIL3', name: 'RUMO S.A.', type: 'ON NM' },
  { simble: 'RENT3', name: 'LOCALIZA', type: 'ON NM' },
  { simble: 'SANB11', name: 'SANTANDER BR', type: 'UNT EJ' },
  { simble: 'SBSP3', name: 'SABESP', type: 'ON NM' },
  { simble: 'SULA11', name: 'SUL AMERICA', type: 'UNT N2' },
  { simble: 'SUZB3', name: 'SUZANO S.A.', type: 'ON NM' },
  { simble: 'TAEE11', name: 'TAESA', type: 'UNT EDJ N2' },
  { simble: 'TIMP3', name: 'TIM PART S/A', type: 'ON NM' },
  { simble: 'TOTS3', name: 'TOTVS', type: 'ON EJ NM' },
  { simble: 'UGPA3', name: 'ULTRAPAR', type: 'ON NM' },
  { simble: 'USIM5', name: 'USIMINAS', type: 'PNA N1' },
  { simble: 'VALE3', name: 'VALE', type: 'ON NM' },
  { simble: 'VIVT4', name: 'TELEF BRASIL', type: 'PN' },
  { simble: 'VVAR3', name: 'VIAVAREJO', type: 'ON NM' },
  { simble: 'WEGE3', name: 'WEG', type: 'ON NM' },
  { simble: 'YDUQ3', name: 'YDUQS PART', type: 'ON NM' },
];

export default allStocks;
